Resolves #64:
clix-meta/clix-meta pull request #65
Opened 2022-08-08 12:41 UTC by larsbarring

* corrected standard name of HD17
* changed long names of HD17 and GD4 as per suggestion
* made same changes to long names of HDDHEAT and CDDCOLD
* changed long names of DDGT and DDLT (different wording)

2022-09-19 09:29 UTC, gstrandb requested changes
Fix typo
Cell K90 "whne" -> "when"

2022-09-19 09:52 UTC, larsbarring commented
Thanks for spotting, should be fixed now.

2022-09-22 06:06 UTC, gstrandb reviewed
Just to be sure. Was this review about checking that the proposed changes were done correctly? Or did I miss something.

Edit: I thought that I could approve after leaving a comment, but that doesn't seem possible. Sorry for the trouble.

2022-09-23 09:14 UTC, gstrandb approved these changes

2022-09-23 09:16 UTC, merged